name: Transcript to AI Voice

on:
  workflow_dispatch:
    inputs:
      access_token:
        description: 'Access token to run workflow'
        required: true
        default: ''
      transcript:
        description: 'Transcript to convert to AI voice'
        required: true
        default: ''
  repository_dispatch:
    types: [run-transcript-to-ai-voice]

jobs:
  validate-parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Validate parameters
        env:
          SECRET_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # Determine event type and extract inputs
          event_name="${{ github.event_name }}"
          if [ "$event_name" = "workflow_dispatch" ]; then
            access_token="${{ inputs.access_token }}"
            transcript="${{ inputs.transcript }}"
          elif [ "$event_name" = "repository_dispatch" ]; then
            access_token="${{ github.event.client_payload.access_token }}"
            transcript="${{ github.event.client_payload.transcript }}"
          else
            echo "Unsupported event type."
            exit 1
          fi

          # Validate access token
          if [ "$access_token" != "$SECRET_ACCESS_TOKEN" ]; then
            echo "Invalid token to run workflow."
            exit 1
          fi

          # Validate transcript length
          if [ ${#transcript} -ge 300 ]; then
            echo "Transcript exceeds 300 characters."
            exit 1
          fi

          # Split transcript into sentences
          IFS='.' read -ra sentences <<< "$transcript"

          # Validate sentence count
          if [ "${#sentences[@]}" -gt 10 ]; then
            echo "Transcript contains more than 10 sentences."
            exit 1
          fi

          # Prepare JSON array of sentences
          sentences_json="["
          for sentence in "${sentences[@]}"; do
            trimmed_sentence=$(echo "$sentence" | xargs) # Trim whitespace
            if [ -n "$trimmed_sentence" ]; then
              sentences_json="$sentences_json\"$trimmed_sentence\","
            fi
          done
          sentences_json="${sentences_json%,}]" # Remove trailing comma and close JSON array

          echo "Sentences JSON: $sentences_json"
          echo "::set-output name=sentences-json::$sentences_json"
  
  run-text-to-speech-action:
    needs: validate-parameters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sentence: ${{ fromJson(needs.validate-parameters.outputs.sentences-json) }}
    steps:
      - name: Run text to speech action for sentence
        uses: ./generate-text-to-speech
        with:
          sentence: ${{ matrix.sentence }}